plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.testng:testng:7.6.1'
    implementation 'org.seleniumhq.selenium:selenium-java:4.5.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:6.0.1'
}

test {
    useTestNG() {
        // Read suite XML
        def suiteFilePath = "src/test/resources/TestNG.xml"
        def suiteText = file(suiteFilePath).text
        def tempSuiteFile = file("${layout.buildDirectory.get()}/tmp/temp-suite.xml")
        tempSuiteFile.parentFile.mkdirs()
        tempSuiteFile.text = suiteText

        suites tempSuiteFile

        // Include groups dynamically from Gradle property 'suite'
        def suiteName = project.findProperty('suite') ?: 'smoke'
        includeGroups suiteName
    }

    reports {
        junitXml.required.set(true)
        html.required.set(true)
    }

    systemProperty "testType", project.findProperty('suite') ?: "smoke"
}
